.\" $Id: luac.man,v 1.29 2011/11/16 13:53:40 lhf Exp $
.TH LUAC 1 "$Date: 2011/11/16 13:53:40 $"
.SH NAME
luac \- Lua 编译器
.SH SYNOPSIS
.B luac
[
.I options
] [
.I filenames
]
.SH DESCRIPTION
.B luac
是 Lua 编译器。
它将用 Lua 编程语言编写的程序
翻译成包含预编译代码块的二进制文件，
这些文件可以稍后加载和执行。
.LP
预编译代码块的主要优点是：
更快的加载速度、
保护源代码免受意外用户更改、
以及脱机语法检查。
预编译并不意味着更快的执行，
因为在 Lua 中，代码块在执行之前总是被编译成字节码。
.B luac
只是允许将这些字节码保存在文件中以供稍后执行。
预编译的代码块不一定比相应的源代码小。
预编译的主要目标是更快的加载。
.LP
在命令行中，
你可以混合包含 Lua 源代码的文本文件
和包含预编译代码块的二进制文件。
.B luac
生成一个包含所有给定文件组合字节码的单一输出文件。
执行组合文件等同于执行给定的文件。
默认情况下，
输出文件名为
.BR luac.out ,
但你可以使用
.B \-o
选项更改它。
.LP
预编译的代码块在不同体系结构之间
.I 不
可移植。
此外，
预编译代码块的内部格式
在发布新版本 Lua 时可能会发生变化。
确保保存你预编译的所有 Lua 程序的源文件。
.LP
.SH OPTIONS
.TP
.B \-l
生成 Lua 虚拟机的编译字节码列表。
列出字节码有助于了解 Lua 的虚拟机。
如果没有给出文件，则
.B luac
加载
.B luac.out
并列出其内容。
使用
.B \-l \-l
获取完整列表。
.TP
.BI \-o " file"
输出到
.I file ,
而不是默认的
.BR luac.out .
（你可以使用
.B "'-'"
表示标准输出，
但在以文本模式打开标准输出的平台上不可用。）
输出文件可能是给定文件之一，
因为所有文件在写入输出文件之前都会被加载。
注意不要覆盖重要文件。
.TP
.B \-p
加载文件但不生成任何输出文件。
主要用于语法检查和测试预编译代码块：
损坏的文件在加载时可能会生成错误。
如果没有给出文件，则
.B luac
加载
.B luac.out
并测试其内容。
如果文件加载无错误则不显示消息。
.TP
.B \-s
在写入输出文件之前剥离调试信息。
这可以节省非常大的代码块的一些空间，
但如果在运行剥离的代码块时发生错误，
则错误消息可能不包含通常的完整信息。
特别是，
行号和局部变量名会丢失。
.TP
.B \-v
显示版本信息。
.TP
.B \-\-
停止处理选项。
.TP
.B \-
停止处理选项并处理标准输入。
.SH "SEE ALSO"
.BR lua (1)
.br
lua.org 上的文档。
.SH DIAGNOSTICS
错误消息应该是自解释的。
.SH AUTHORS
R. Ierusalimschy,
L. H. de Figueiredo,
W. Celes
.\" EOF
